//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_CS_OKCASA_G7.WSINICIARSESION {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="WSINICIARSESION.WSLOGIN")]
    public interface WSLOGIN {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSLOGIN/RutUsuarioRequest", ReplyAction="http://ws/WSLOGIN/RutUsuarioResponse")]
        APP_CS_OKCASA_G7.WSINICIARSESION.RutUsuarioResponse RutUsuario(APP_CS_OKCASA_G7.WSINICIARSESION.RutUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSLOGIN/RutUsuarioRequest", ReplyAction="http://ws/WSLOGIN/RutUsuarioResponse")]
        System.Threading.Tasks.Task<APP_CS_OKCASA_G7.WSINICIARSESION.RutUsuarioResponse> RutUsuarioAsync(APP_CS_OKCASA_G7.WSINICIARSESION.RutUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSLOGIN/LoginRequest", ReplyAction="http://ws/WSLOGIN/LoginResponse")]
        APP_CS_OKCASA_G7.WSINICIARSESION.LoginResponse Login(APP_CS_OKCASA_G7.WSINICIARSESION.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSLOGIN/LoginRequest", ReplyAction="http://ws/WSLOGIN/LoginResponse")]
        System.Threading.Tasks.Task<APP_CS_OKCASA_G7.WSINICIARSESION.LoginResponse> LoginAsync(APP_CS_OKCASA_G7.WSINICIARSESION.LoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RutUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RutUsuario", Namespace="http://ws/", Order=0)]
        public APP_CS_OKCASA_G7.WSINICIARSESION.RutUsuarioRequestBody Body;
        
        public RutUsuarioRequest() {
        }
        
        public RutUsuarioRequest(APP_CS_OKCASA_G7.WSINICIARSESION.RutUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RutUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public RutUsuarioRequestBody() {
        }
        
        public RutUsuarioRequestBody(string usuario, string pass) {
            this.usuario = usuario;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RutUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RutUsuarioResponse", Namespace="http://ws/", Order=0)]
        public APP_CS_OKCASA_G7.WSINICIARSESION.RutUsuarioResponseBody Body;
        
        public RutUsuarioResponse() {
        }
        
        public RutUsuarioResponse(APP_CS_OKCASA_G7.WSINICIARSESION.RutUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RutUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public RutUsuarioResponseBody() {
        }
        
        public RutUsuarioResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://ws/", Order=0)]
        public APP_CS_OKCASA_G7.WSINICIARSESION.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(APP_CS_OKCASA_G7.WSINICIARSESION.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string usuario, string pass) {
            this.usuario = usuario;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://ws/", Order=0)]
        public APP_CS_OKCASA_G7.WSINICIARSESION.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(APP_CS_OKCASA_G7.WSINICIARSESION.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSLOGINChannel : APP_CS_OKCASA_G7.WSINICIARSESION.WSLOGIN, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSLOGINClient : System.ServiceModel.ClientBase<APP_CS_OKCASA_G7.WSINICIARSESION.WSLOGIN>, APP_CS_OKCASA_G7.WSINICIARSESION.WSLOGIN {
        
        public WSLOGINClient() {
        }
        
        public WSLOGINClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSLOGINClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSLOGINClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSLOGINClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APP_CS_OKCASA_G7.WSINICIARSESION.RutUsuarioResponse APP_CS_OKCASA_G7.WSINICIARSESION.WSLOGIN.RutUsuario(APP_CS_OKCASA_G7.WSINICIARSESION.RutUsuarioRequest request) {
            return base.Channel.RutUsuario(request);
        }
        
        public string RutUsuario(string usuario, string pass) {
            APP_CS_OKCASA_G7.WSINICIARSESION.RutUsuarioRequest inValue = new APP_CS_OKCASA_G7.WSINICIARSESION.RutUsuarioRequest();
            inValue.Body = new APP_CS_OKCASA_G7.WSINICIARSESION.RutUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.pass = pass;
            APP_CS_OKCASA_G7.WSINICIARSESION.RutUsuarioResponse retVal = ((APP_CS_OKCASA_G7.WSINICIARSESION.WSLOGIN)(this)).RutUsuario(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APP_CS_OKCASA_G7.WSINICIARSESION.RutUsuarioResponse> APP_CS_OKCASA_G7.WSINICIARSESION.WSLOGIN.RutUsuarioAsync(APP_CS_OKCASA_G7.WSINICIARSESION.RutUsuarioRequest request) {
            return base.Channel.RutUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<APP_CS_OKCASA_G7.WSINICIARSESION.RutUsuarioResponse> RutUsuarioAsync(string usuario, string pass) {
            APP_CS_OKCASA_G7.WSINICIARSESION.RutUsuarioRequest inValue = new APP_CS_OKCASA_G7.WSINICIARSESION.RutUsuarioRequest();
            inValue.Body = new APP_CS_OKCASA_G7.WSINICIARSESION.RutUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.pass = pass;
            return ((APP_CS_OKCASA_G7.WSINICIARSESION.WSLOGIN)(this)).RutUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APP_CS_OKCASA_G7.WSINICIARSESION.LoginResponse APP_CS_OKCASA_G7.WSINICIARSESION.WSLOGIN.Login(APP_CS_OKCASA_G7.WSINICIARSESION.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public int Login(string usuario, string pass) {
            APP_CS_OKCASA_G7.WSINICIARSESION.LoginRequest inValue = new APP_CS_OKCASA_G7.WSINICIARSESION.LoginRequest();
            inValue.Body = new APP_CS_OKCASA_G7.WSINICIARSESION.LoginRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.pass = pass;
            APP_CS_OKCASA_G7.WSINICIARSESION.LoginResponse retVal = ((APP_CS_OKCASA_G7.WSINICIARSESION.WSLOGIN)(this)).Login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APP_CS_OKCASA_G7.WSINICIARSESION.LoginResponse> APP_CS_OKCASA_G7.WSINICIARSESION.WSLOGIN.LoginAsync(APP_CS_OKCASA_G7.WSINICIARSESION.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<APP_CS_OKCASA_G7.WSINICIARSESION.LoginResponse> LoginAsync(string usuario, string pass) {
            APP_CS_OKCASA_G7.WSINICIARSESION.LoginRequest inValue = new APP_CS_OKCASA_G7.WSINICIARSESION.LoginRequest();
            inValue.Body = new APP_CS_OKCASA_G7.WSINICIARSESION.LoginRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.pass = pass;
            return ((APP_CS_OKCASA_G7.WSINICIARSESION.WSLOGIN)(this)).LoginAsync(inValue);
        }
    }
}
